repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.7
  # TODO markdownlint broken
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.11.0
  #   hooks:
  #     - id: markdownlint
  #       args: [-s, .ml_style.rb, README.md]
  #       exclude: GitHubRepoPublicReleaseApproval.md|LICENSE.md
