stepped_frequency_time_domain_subdev:
  name: acquire_CW_lab_AB_GPS_35_10
  fcs:
    - 3480e6
    - 3480e6
  gains:
    - 60
    - 60
  sample_rates:
    - 10e6
    - 10e6
  durations_ms:
    - 1000
    - 1000
  subdev:
    - A:B
    - A:B
  gps_clock:
    - True
    - True
