stepped_frequency_time_domain_iq:
  name: acquire_CW_home_01
  fcs:
    - 700e6
    - 700e6
    - 700e6
    - 700e6
    - 700e6
    - 700e6
  gains:
    - 40
    - 60
    - 40
    - 60
    - 40
    - 60
  sample_rates:
    - 5e6
    - 5e6
    - 10e6
    - 10e6
    - 20e6
    - 20e6
  durations_ms:
    - 2000
    - 2000
    - 2000
    - 2000
    - 2000
    - 2000