stepped_frequency_time_domain_subdev:
  name: acquire_CW_TM_AA_internal
  fcs:
    - 5800e6
    - 5800e6
  gains:
    - 60
    - 60
  sample_rates:
    - 5e6
    - 5e6
  durations_ms:
    - 1000
    - 1000
  subdev:
    - A:A
    - A:A
  gps_clock:
    - False
    - False