stepped_frequency_time_domain_subdev:
  name: acquire_CW_TM_AB_GPS_40
  fcs:
    - 5800e6
    - 5800e6
  gains:
    - 40
    - 40
  sample_rates:
    - 5e6
    - 5e6
  durations_ms:
    - 1000
    - 1000
  subdev:
    - A:B
    - A:B
  gps_clock:
    - True
    - True
