stepped_frequency_time_domain_iq:
  name: acquire_CW_TM_01
  fcs:
    - 5790e6
    - 5790e6
    - 5790e6
    - 5790e6
  gains:
    - 40
    - 60
    - 40
    - 60
  sample_rates:
    - 5e6
    - 5e6
    - 10e6
    - 10e6
  durations_ms:
    - 2000
    - 2000
    - 2000
    - 2000
  subdev:
    - A:A
    - A:A
    - A:A
    - A:A