stepped_frequency_time_domain_subdev:
  name: acquire_CW_TM_subdev_01
  fcs:
    - 5790e6
    - 5790e6
  gains:
    - 60
    - 60
  sample_rates:
    - 5e6
    - 10e6
  durations_ms:
    - 1000
    - 1000
  subdev:
    - A:B
    - A:B