stepped_frequency_time_domain_subdev:
  name: acquire_TM_AB_GPS_40M
  fcs:
    - 5800e6
    - 5800e6
  gains:
    - 60
    - 60
  sample_rates:
    - 40e6
    - 40e6
  durations_ms:
    - 1000
    - 1000
  subdev:
    - A:B
    - A:B
  gps_clock:
    - True
    - True
