stepped_frequency_time_domain_iq:
  name: test_multi_frequency_iq_action
  frequency:
    - 700.5e6
    - 709e6
    - 731.5e6
    - 739e6
    - 751e6
    - 763e6
    - 772e6
    - 782e6
    - 793e6
    - 802e6
  gain: 40
  sample_rate: 15.36e6
  duration_ms: 80
  nskip: 15.36e4
  calibration_adjust: False
  classification: UNCLASSIFIED
  rf_path: antenna
