y_factor_cal:
  name: test_single_frequency_y_factor_action
  # Preselector configuration
  cal_source_idx: 0  # Index of calibration source in preselector
  temp_sensor_idx: 1  # Index of temperature sensor in preselector
  # Sigan Settings
  gain: 40
  sample_rate: 15.36e6
  duration_ms: 1000
  nskip: 15.36e4
  frequency: 739e6
  # IIR Filter Settings
  iir_apply: True
  iir_rp_dB: 0.1
  iir_rs_dB: 40
  iir_cutoff_Hz: 7.68e6
  iir_width_Hz: 8e3