single_frequency_time_domain_iq:
  name: test_single_frequency_iq_action
  frequency: 739e6
  gain: 40
  sample_rate: 15.36e6
  duration_ms: 1000
  nskip: 15.36e4
  calibration_adjust: False
  classification: UNCLASSIFIED
