transmit_pn:
  name: transmit_PN_TM_AA_GPS_1m_12bit_10MHz
  center_frequency: 5800e6
  gain: 90
  sample_rate: 10e6
  duration_ms: 60000
  seed: [0, 0, 0, 0, 0, 0, 0, 0, 1]
  sampspersymbol: 12
  subdev: A:A
  gps_clock: True
