transmit_pn:
  name: transmit_PN_TM_AB_GPS_1m_4bit_20M
  center_frequency: 5800e6
  gain: 90
  sample_rate: 20e6
  duration_ms: 60000
  seed: [0, 0, 0, 0, 0, 0, 0, 0, 1]
  sampspersymbol: 4
  subdev: A:B
  gps_clock: True
