transmit_pn:
  name: transmit_PN_TM_AB_GPS_1m_8bit
  center_frequency: 5800e6
  gain: 90
  sample_rate: 5e6
  duration_ms: 60000
  seed: [0, 0, 0, 0, 0, 0, 0, 0, 1]
  sampspersymbol: 8
  subdev: A:B
  gps_clock: True
