name: Tox

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - scos_actions
  pull_request:
    branches:
      - master
    paths:
      - scos_actions

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progess: true

jobs:
  run-all-tests:
    name: Py${{ matrix.py }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-latest
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
      steps:
        - name: Set up Python ${{ matrix.py }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.py }}
        - name: Checkout scos-actions
          uses: actions/checkout@v3
        - name: Install tox-gh
          run: python -m pip install tox-gh
        - name: Set up test suite
          run: tox r -vv --notest
        - name: Run test suite
          run: tox r --skip-pkg-install
          env:
            PYTEST_ADDOPTS: "-vv --durations=0"
